# Holds constants for the whole program

UDP_PORT_NUMBER = 54545
SERVER_CONNECTION_PORT_NUMBER = 54546
CLIENT_CONNECTION_PORT_NUMBER = 54547

ANY_IP = "0.0.0.0"
SERVER_ONLY_IP = "255.255.0.1"

DEVICE_NAME_FILE = "device_name.json"

JSON_MESSAGE_TYPE = "message_type"
JSON_MESSAGE_TYPE_ANNOUNCE_CLIENT = "announce_client"
JSON_MESSAGE_TYPE_POLL = "poll"
JSON_MESSAGE_TYPE_DATA = "data"
JSON_MESSAGE_TYPE_INSTALL_USER = "install_user"
JSON_MESSAGE_TYPE_INSTALL_STATUS = "install_status"

JSON_CLIENT_NAME = "client_name"
JSON_IP_ADDRESS = "ip_address"
JSON_TIME = "clock_time"
JSON_STATUS = "status"
JSON_STATUS_OK = "ok"
JSON_STATUS_FAIL = "fail"
JSON_USER_ID = "user_id"
JSON_USER_PERMISSION = "user_permission"
JSON_ACCESS_GRANTED = "access_granted"
JSON_ACCESS_DENIED = "access_denied"

JSON_TIME_FORMAT = "%H:%M:%S"

NO_DATA = "NO DATA"
