# Holds constants for the whole program

UDP_PORT_NUMBER = 54545
SERVER_CONNECTION_PORT_NUMBER = 54546
CLIENT_CONNECTION_PORT_NUMBER = 54547

ANY_IP = "0.0.0.0"
SERVER_ONLY_IP = "255.255.0.1"

JSON_MESSAGE_TYPE = "message_type"
JSON_MESSAGE_TYPE_ANNOUNCE = "announce"
JSON_MESSAGE_TYPE_POLL = "poll"
JSON_MESSAGE_TYPE_DATA = "data"
JSON_MESSAGE_TYPE_INSTALL = "install"
JSON_MESSAGE_TYPE_INSTALL_STATUS = "install_status"
JSON_MESSAGE_TYPE_UPDATE = "update"
JSON_MESSAGE_TYPE_UPDATE_STATUS = "update_status"

JSON_CLIENT_NAME = "name"
JSON_IP_ADDRESS = "ip_address"
JSON_TIME = "clock_time"
JSON_DATA_TYPE = "data_type"
JSON_STATUS = "status"
JSON_STATUS_OK = "ok"
JSON_STATUS_FAIL = "fail"
JSON_UPDATE_TIMESTAMP = "last_updated"

JSON_TIME_FORMAT = "%H:%M:%S"
